# Generated by Django 5.1.6 on 2025-02-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0004_device_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpsecProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('protocol', models.CharField(choices=[('esp', 'ESP'), ('ah', 'AH')], default='esp', max_length=10)),
                ('authentication_algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA1'), ('sha256', 'SHA256'), ('sha384', 'SHA384'), ('sha512', 'SHA512')], max_length=50)),
                ('encryption_algorithm', models.CharField(choices=[('3des', '3DES'), ('aes-128-cbc', 'AES-128-CBC'), ('aes-192-cbc', 'AES-192-CBC'), ('aes-256-cbc', 'AES-256-CBC'), ('aes-128-gcm', 'AES-128-GCM'), ('aes-256-gcm', 'AES-256-GCM')], max_length=50)),
                ('dh_group', models.CharField(choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group5', 'Group 5'), ('group14', 'Group 14'), ('group19', 'Group 19'), ('group20', 'Group 20')], max_length=20)),
                ('lifetime_seconds', models.PositiveIntegerField(default=86400)),
                ('lifetime_kilobytes', models.PositiveIntegerField(default=64000)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
            ],
        ),
    ]
