# Generated by Django 5.2.1 on 2025-07-02 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
        ('ipsecs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsecvpn',
            name='bind_interface',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interfaces.interface'),
        ),
    ]
