# Generated by Django 5.1.6 on 2025-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsecvpn',
            name='bind_interface',
            field=models.CharField(default='g0/0/0', max_length=50),
        ),
    ]
