# Generated by Django 5.1.6 on 2025-02-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
        ('ipsecs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsecproposal',
            name='devices',
            field=models.ManyToManyField(to='inventories.device'),
        ),
        migrations.AlterField(
            model_name='ipsecproposal',
            name='lifetime_seconds',
            field=models.PositiveIntegerField(default=86400),
        ),
    ]
