# Generated by Django 5.2.1 on 2025-06-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_alter_device_keepalive'),
        ('ipsecs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikegateway',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ike_gateways', to='inventories.device'),
        ),
        migrations.AlterField(
            model_name='ikegateway',
            name='external_interface',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ikegateway',
            name='ike_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ike_gateways', to='ipsecs.ikepolicy'),
        ),
        migrations.AlterField(
            model_name='ikepolicy',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ike_policies', to='inventories.device'),
        ),
        migrations.AlterField(
            model_name='ikepolicy',
            name='proposals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ike_policies', to='ipsecs.ikeproposal'),
        ),
        migrations.AlterField(
            model_name='ikeproposal',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ike_proposals', to='inventories.device'),
        ),
        migrations.AlterField(
            model_name='ipsecpolicy',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipsec_policies', to='inventories.device'),
        ),
        migrations.AlterField(
            model_name='ipsecpolicy',
            name='ipsec_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipsec_policies_for_proposal', to='ipsecs.ipsecproposal'),
        ),
        migrations.AlterField(
            model_name='ipsecproposal',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipsec_proposals', to='inventories.device'),
        ),
        migrations.AlterField(
            model_name='ipsecvpn',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipsec_vpns', to='inventories.device'),
        ),
        migrations.AlterField(
            model_name='ipsecvpn',
            name='ike_gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipsec_vpns_for_gateway', to='ipsecs.ikegateway'),
        ),
        migrations.AlterField(
            model_name='ipsecvpn',
            name='ipsec_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipsec_vpns_for_policy', to='ipsecs.ipsecpolicy'),
        ),
    ]
