# Generated by Django 5.2 on 2025-05-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0002_remove_ikepolicy_authentication_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikeproposal',
            name='proposalname',
            field=models.CharField(max_length=100, verbose_name='IKE Proposal Name'),
        ),
    ]
