# Generated by Django 5.1.6 on 2025-02-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0002_alter_ipsecproposal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipsecproposal',
            old_name='devices',
            new_name='device',
        ),
    ]
