# Generated by Django 5.1.6 on 2025-03-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0002_alter_ipsecvpn_bind_interface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ikeproposal',
            name='lifetime_kilobytes',
        ),
        migrations.RemoveField(
            model_name='ikeproposal',
            name='protocol',
        ),
        migrations.AlterField(
            model_name='ikeproposal',
            name='dh_group',
            field=models.CharField(choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group5', 'Group 5'), ('group14', 'Group 14'), ('group15', 'Group 15'), ('group16', 'Group 16'), ('group19', 'Group 19'), ('group20', 'Group 20'), ('group21', 'Group 21')], default='group14', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipsecpolicy',
            name='pfs_group',
            field=models.CharField(choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group5', 'Group 5'), ('group14', 'Group 14'), ('group15', 'Group 15'), ('group16', 'Group 16'), ('group19', 'Group 19'), ('group20', 'Group 20'), ('group21', 'Group 21')], default='group14', max_length=20),
        ),
    ]
