# Generated by Django 5.2.1 on 2025-05-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0003_alter_ikeproposal_proposalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikeproposal',
            name='authentication_algorithm',
            field=models.CharField(blank=True, choices=[('md5', 'MD5'), ('sha1', 'SHA1'), ('sha-256', 'SHA-256'), ('sha-384', 'SHA-384'), ('sha-512', 'SHA-512')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ikeproposal',
            name='authentication_method',
            field=models.CharField(choices=[('pre-shared-keys', 'Pre-Shared Keys'), ('rsa', 'RSA')], default='pre-shared-keys', max_length=20),
        ),
        migrations.AlterField(
            model_name='ikeproposal',
            name='encryption_algorithm',
            field=models.CharField(choices=[('3des-cbc', '3DES-CBC'), ('aes-128-cbc', 'AES-128-CBC'), ('aes-192-cbc', 'AES-192-CBC'), ('aes-256-cbc', 'AES-256-CBC'), ('aes-128-gcm', 'AES-128-GCM'), ('aes-256-gcm', 'AES-256-GCM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ipsecproposal',
            name='authentication_algorithm',
            field=models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA1'), ('sha-256', 'SHA-256'), ('sha-384', 'SHA-384'), ('sha-512', 'SHA-512')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ipsecproposal',
            name='encryption_algorithm',
            field=models.CharField(choices=[('3des-cbc', '3DES-CBC'), ('aes-128-cbc', 'AES-128-CBC'), ('aes-192-cbc', 'AES-192-CBC'), ('aes-256-cbc', 'AES-256-CBC'), ('aes-128-gcm', 'AES-128-GCM'), ('aes-256-gcm', 'AES-256-GCM')], max_length=50),
        ),
    ]
