# Generated by Django 5.1.6 on 2025-02-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_alter_device_device_name'),
        ('ipsecs', '0003_rename_devices_ipsecproposal_device'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IpsecProposal',
            new_name='IkeProposal',
        ),
    ]
