# Generated by Django 5.2.1 on 2025-05-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0004_alter_ikeproposal_authentication_algorithm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikepolicy',
            name='policyname',
            field=models.CharField(max_length=100),
        ),
    ]
