# Generated by Django 5.2.1 on 2025-05-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0005_alter_ikepolicy_policyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikegateway',
            name='gatewayname',
            field=models.CharField(max_length=100),
        ),
    ]
