# Generated by Django 5.1.7 on 2025-03-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0005_rename_name_ikepolicy_policyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ikegateway',
            old_name='name',
            new_name='gatewayname',
        ),
    ]
