# Generated by Django 5.2.1 on 2025-05-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0007_rename_proposal_name_ipsecproposal_proposalname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipsecproposal',
            name='dh_group',
        ),
    ]
