# Generated by Django 5.2.1 on 2025-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0008_remove_ipsecproposal_dh_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsecpolicy',
            name='policy_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ipsecproposal',
            name='proposalname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ipsecvpn',
            name='vpn_name',
            field=models.CharField(max_length=100),
        ),
    ]
