# Generated by Django 5.2.1 on 2025-06-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0009_alter_ipsecpolicy_policy_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsecproposal',
            name='lifetime_seconds',
            field=models.PositiveIntegerField(default=86400),
        ),
        migrations.AlterField(
            model_name='ipsecproposal',
            name='authentication_algorithm',
            field=models.CharField(blank=True, choices=[('hmac-md5-96', 'Md5'), ('hmac-sha-256-128', 'Sha'), ('hmac-sha1-96', 'Sha1')], default='hmac-sha-256-128', max_length=50, null=True),
        ),
    ]
