# Generated by Django 5.2.7 on 2025-11-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='addresses_a_zone_id_d01052_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zone',
        ),
    ]
