# Generated by Django 5.2.7 on 2025-11-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_remove_address_addresses_a_zone_id_d01052_idx_and_more'),
        ('inventories', '0008_alter_device_keepalive'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.device'),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='addresses.address'),
        ),
    ]
