# Generated by Django 5.2.7 on 2025-11-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_device_alter_addressbook_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
