# Generated by Django 5.2.7 on 2025-12-20 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_alter_address_name'),
        ('security', '0003_remove_securityzone_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='attached_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.securityzone'),
        ),
    ]
