# Generated by Django 5.2.7 on 2025-12-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_addressbook_attached_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='addresses',
        ),
        migrations.AddField(
            model_name='address',
            name='addressbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='addresses.addressbook'),
        ),
    ]
