# Generated by Django 5.2.7 on 2025-12-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_remove_addressbook_addresses_address_addressbook'),
        ('inventories', '0008_alter_device_keepalive'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.device'),
        ),
    ]
