# Generated by Django 5.2.7 on 2025-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0008_addressbook_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
