# Generated by Django 5.2.7 on 2025-12-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0009_alter_addressbook_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
