export const PAGESIZE = 'PAGESIZE';
export const CURRENTPAGE = 'CURRENTPAGE';
export const FILTEREDIPSECDATA = 'FILTEREDIPSECDATA';
export const SELECTEDOPTIONS = 'SELECTEDOPTIONS';
export const UPDATEDOPTIONS = 'UPDATEDOPTIONS';
export const APIDATA = 'APIDATA';
