# Generated by Django 5.2.7 on 2025-11-02 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interfaces', '0001_initial'),
        ('inventories', '0008_alter_device_keepalive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cidr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('system_services', models.JSONField(default=list)),
                ('system_protocols', models.JSONField(default=list)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('addresses', models.ManyToManyField(blank=True, related_name='zones', to='security.address')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_zones', to='inventories.device')),
                ('interfaces', models.ManyToManyField(blank=True, related_name='zones', to='interfaces.interface')),
            ],
            options={
                'ordering': ['zone_name'],
                'unique_together': {('device', 'zone_name')},
            },
        ),
    ]
