# Generated by Django 5.2.7 on 2025-11-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_device_alter_addressbook_addresses'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AlterField(
            model_name='securityzone',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='zones', to='addresses.address'),
        ),
    ]
