# Generated by Django 5.2.4 on 2025-10-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_alter_device_keepalive'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityzone',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='securityzone',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventories.device'),
        ),
        migrations.AddField(
            model_name='securityzone',
            name='system_protocols',
            field=models.JSONField(default=list),
        ),
    ]
