# Generated by Django 5.2.7 on 2025-12-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_delete_address_alter_securityzone_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityzone',
            name='addresses',
        ),
    ]
