# Generated by Django 5.1.7 on 2025-04-24 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IkePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyname', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('main', 'Main'), ('aggressive', 'Aggressive')], max_length=50)),
                ('authentication_method', models.CharField(choices=[('pre-shared-key', 'Pre-Shared Key'), ('rsa', 'RSA')], default='pre-shared-key', max_length=20)),
                ('pre_shared_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
            ],
        ),
        migrations.CreateModel(
            name='IkeGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayname', models.CharField(max_length=100, unique=True)),
                ('remote_address', models.GenericIPAddressField()),
                ('local_address', models.GenericIPAddressField()),
                ('external_interface', models.CharField(default='g0/0/0', max_length=50)),
                ('ike_version', models.CharField(choices=[('v1-only', 'v1-only'), ('v2-only', 'v2-only')], default='v1-only', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
                ('ike_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsecs.ikepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='IkeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposalname', models.CharField(help_text='A unique name for this IKE proposal', max_length=100, unique=True, verbose_name='IKE Proposal Name')),
                ('authentication_algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA1'), ('sha256', 'SHA256'), ('sha384', 'SHA384'), ('sha512', 'SHA512')], max_length=50)),
                ('encryption_algorithm', models.CharField(choices=[('3des', '3DES'), ('aes-128-cbc', 'AES-128-CBC'), ('aes-192-cbc', 'AES-192-CBC'), ('aes-256-cbc', 'AES-256-CBC'), ('aes-128-gcm', 'AES-128-GCM'), ('aes-256-gcm', 'AES-256-GCM')], max_length=50)),
                ('dh_group', models.CharField(choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group5', 'Group 5'), ('group14', 'Group 14'), ('group15', 'Group 15'), ('group16', 'Group 16'), ('group19', 'Group 19'), ('group20', 'Group 20'), ('group21', 'Group 21')], default='group14', max_length=20)),
                ('lifetime_seconds', models.PositiveIntegerField(default=86400)),
                ('is_published', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
            ],
            options={
                'verbose_name': 'IKE Proposal',
                'verbose_name_plural': 'IKE Proposals',
                'ordering': ['proposalname'],
            },
        ),
        migrations.AddField(
            model_name='ikepolicy',
            name='proposals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipsecs.ikeproposal'),
        ),
        migrations.CreateModel(
            name='IpsecPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('pfs_group', models.CharField(choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group5', 'Group 5'), ('group14', 'Group 14'), ('group15', 'Group 15'), ('group16', 'Group 16'), ('group19', 'Group 19'), ('group20', 'Group 20'), ('group21', 'Group 21')], default='group14', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
                ('ike_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipsecs.ikeproposal')),
            ],
        ),
        migrations.CreateModel(
            name='IpsecProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_name', models.CharField(max_length=100, unique=True)),
                ('authentication_algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA1'), ('sha256', 'SHA256'), ('sha384', 'SHA384'), ('sha512', 'SHA512')], max_length=50)),
                ('encryption_algorithm', models.CharField(choices=[('3des', '3DES'), ('aes-128-cbc', 'AES-128-CBC'), ('aes-192-cbc', 'AES-192-CBC'), ('aes-256-cbc', 'AES-256-CBC'), ('aes-128-gcm', 'AES-128-GCM'), ('aes-256-gcm', 'AES-256-GCM')], max_length=50)),
                ('encapsulation_protocol', models.CharField(choices=[('esp', 'ESP'), ('ah', 'AH')], default='esp', max_length=50)),
                ('dh_group', models.CharField(choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group5', 'Group 5'), ('group14', 'Group 14'), ('group15', 'Group 15'), ('group16', 'Group 16'), ('group19', 'Group 19'), ('group20', 'Group 20'), ('group21', 'Group 21')], default='group14', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
            ],
        ),
        migrations.CreateModel(
            name='IpsecVpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpn_name', models.CharField(max_length=100, unique=True)),
                ('bind_interface', models.CharField(default='g0/0/0', max_length=50)),
                ('establish_tunnel', models.CharField(choices=[('immediately', 'immediately'), ('on-traffic', 'on-traffic')], default='immediately', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
                ('ike_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsecs.ikegateway')),
                ('ipsec_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsecs.ipsecpolicy')),
            ],
        ),
    ]
