# Generated by Django 5.2 on 2025-04-11 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0002_device_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='IkePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyname', models.CharField(max_length=100, unique=True)),
                ('authentication_method', models.CharField(choices=[('psk', 'Pre-Shared Key'), ('rsa', 'RSA')], default='psk', max_length=20)),
                ('pre_shared_key', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
            ],
        ),
        migrations.CreateModel(
            name='IkeGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayname', models.CharField(max_length=100, unique=True)),
                ('remote_address', models.GenericIPAddressField()),
                ('local_interface', models.CharField(max_length=50)),
                ('external_interface', models.CharField(default='g0/0/0', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
                ('ike_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsecs.ikepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='IkeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposalname', models.CharField(max_length=100, unique=True)),
                ('authentication_algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA1'), ('sha256', 'SHA256'), ('sha384', 'SHA384'), ('sha512', 'SHA512')], max_length=50)),
                ('encryption_algorithm', models.CharField(choices=[('3des', '3DES'), ('aes-128-cbc', 'AES-128-CBC'), ('aes-192-cbc', 'AES-192-CBC'), ('aes-256-cbc', 'AES-256-CBC'), ('aes-128-gcm', 'AES-128-GCM'), ('aes-256-gcm', 'AES-256-GCM')], max_length=50)),
                ('dh_group', models.CharField(choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group5', 'Group 5'), ('group14', 'Group 14'), ('group15', 'Group 15'), ('group16', 'Group 16'), ('group19', 'Group 19'), ('group20', 'Group 20'), ('group21', 'Group 21')], default='group14', max_length=20)),
                ('lifetime_seconds', models.PositiveIntegerField(default=86400)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
            ],
        ),
        migrations.AddField(
            model_name='ikepolicy',
            name='proposals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipsecs.ikeproposal'),
        ),
        migrations.CreateModel(
            name='IpsecProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('authentication_algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA1'), ('sha256', 'SHA256'), ('sha384', 'SHA384'), ('sha512', 'SHA512')], max_length=50)),
                ('encryption_algorithm', models.CharField(choices=[('3des', '3DES'), ('aes-128-cbc', 'AES-128-CBC'), ('aes-192-cbc', 'AES-192-CBC'), ('aes-256-cbc', 'AES-256-CBC'), ('aes-128-gcm', 'AES-128-GCM'), ('aes-256-gcm', 'AES-256-GCM')], max_length=50)),
                ('lifetime_seconds', models.PositiveIntegerField(default=3600)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
            ],
        ),
        migrations.CreateModel(
            name='IpsecPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyname', models.CharField(max_length=100, unique=True)),
                ('pfs_group', models.CharField(choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group5', 'Group 5'), ('group14', 'Group 14'), ('group15', 'Group 15'), ('group16', 'Group 16'), ('group19', 'Group 19'), ('group20', 'Group 20'), ('group21', 'Group 21')], default='group14', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
                ('proposals', models.ManyToManyField(to='ipsecs.ipsecproposal')),
            ],
        ),
        migrations.CreateModel(
            name='IpsecVpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bind_interface', models.CharField(default='g0/0/0', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.device')),
                ('ike_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsecs.ikegateway')),
                ('ipsec_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsecs.ipsecpolicy')),
            ],
        ),
    ]
