# Generated by Django 5.2 on 2025-04-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ikepolicy',
            name='mode',
            field=models.CharField(choices=[('main', 'Main'), ('aggressive', 'Aggressive')], default='main', max_length=50),
            preserve_default=False,
        ),
    ]
