# Generated by Django 5.2 on 2025-05-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ikepolicy',
            name='authentication_method',
        ),
        migrations.AddField(
            model_name='ikeproposal',
            name='authentication_method',
            field=models.CharField(choices=[('pre-shared-key', 'Pre-Shared Key'), ('rsa', 'RSA')], default='pre-shared-key', max_length=20),
        ),
    ]
