# Generated by Django 5.2 on 2025-04-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0002_ikepolicy_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikepolicy',
            name='authentication_method',
            field=models.CharField(choices=[('pre-shared-key', 'Pre-Shared Key'), ('rsa', 'RSA')], default='pre-shared-key', max_length=20),
        ),
    ]
