# Generated by Django 5.2 on 2025-04-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0003_alter_ikepolicy_authentication_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ikegateway',
            old_name='local_interface',
            new_name='local_address',
        ),
    ]
