# Generated by Django 5.2 on 2025-04-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0004_rename_local_interface_ikegateway_local_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ikegateway',
            name='ike_version',
            field=models.CharField(choices=[('v1-only', 'v1-only'), ('v2-only', 'v2-only')], default='v1-only', max_length=50),
        ),
    ]
