# Generated by Django 5.1.7 on 2025-04-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0005_ikegateway_ike_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ikegateway',
            name='local_address',
            field=models.GenericIPAddressField(),
        ),
    ]
