# Generated by Django 5.1.7 on 2025-04-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0006_alter_ikegateway_local_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipsecproposal',
            old_name='name',
            new_name='proposalname',
        ),
        migrations.RemoveField(
            model_name='ipsecproposal',
            name='lifetime_seconds',
        ),
        migrations.AddField(
            model_name='ipsecproposal',
            name='encap_protocols',
            field=models.CharField(choices=[('esp', 'ESP'), ('ah', 'AH')], default='esp', max_length=50),
        ),
    ]
