# Generated by Django 5.1.7 on 2025-04-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0007_rename_name_ipsecproposal_proposalname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipsecproposal',
            old_name='encap_protocols',
            new_name='encapsulation_protocol',
        ),
    ]
