# Generated by Django 5.1.7 on 2025-04-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0008_rename_encap_protocols_ipsecproposal_encapsulation_protocol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipsecproposal',
            old_name='proposalname',
            new_name='proposal_name',
        ),
    ]
