# Generated by Django 5.1.7 on 2025-04-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0009_rename_proposalname_ipsecproposal_proposal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsecproposal',
            name='dh_group',
            field=models.CharField(choices=[('group1', 'Group 1'), ('group2', 'Group 2'), ('group5', 'Group 5'), ('group14', 'Group 14'), ('group15', 'Group 15'), ('group16', 'Group 16'), ('group19', 'Group 19'), ('group20', 'Group 20'), ('group21', 'Group 21')], default='group14', max_length=20),
        ),
    ]
