# Generated by Django 5.1.7 on 2025-04-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0010_ipsecproposal_dh_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsecpolicy',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='ipsecpolicy',
            name='proposals',
        ),
        migrations.AddField(
            model_name='ipsecpolicy',
            name='proposals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipsecs.ikeproposal'),
        ),
    ]
