# Generated by Django 5.1.7 on 2025-04-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0011_ipsecpolicy_description_remove_ipsecpolicy_proposals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipsecpolicy',
            old_name='proposals',
            new_name='ikeproposals',
        ),
    ]
