# Generated by Django 5.1.7 on 2025-04-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0012_rename_proposals_ipsecpolicy_ikeproposals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipsecpolicy',
            old_name='policyname',
            new_name='policy_name',
        ),
    ]
