# Generated by Django 5.1.7 on 2025-04-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0013_rename_policyname_ipsecpolicy_policy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipsecpolicy',
            old_name='ikeproposals',
            new_name='ike_proposals',
        ),
    ]
