# Generated by Django 5.1.7 on 2025-04-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0014_rename_ikeproposals_ipsecpolicy_ike_proposals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipsecpolicy',
            old_name='ike_proposals',
            new_name='ike_proposal',
        ),
    ]
