# Generated by Django 5.1.7 on 2025-04-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0015_rename_ike_proposals_ipsecpolicy_ike_proposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipsecvpn',
            old_name='name',
            new_name='vpn_name',
        ),
    ]
