# Generated by Django 5.1.7 on 2025-04-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0016_rename_name_ipsecvpn_vpn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsecvpn',
            name='establish_tunnel',
            field=models.CharField(choices=[('immediately', 'immediately'), ('on-traffic', 'on-traffic')], default='immediately', max_length=50),
        ),
    ]
