# Generated by Django 5.1.7 on 2025-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0017_ipsecvpn_establish_tunnel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ikeproposal',
            options={'ordering': ['proposalname'], 'verbose_name': 'IKE Proposal', 'verbose_name_plural': 'IKE Proposals'},
        ),
        migrations.AddField(
            model_name='ikeproposal',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ikeproposal',
            name='proposalname',
            field=models.CharField(help_text='A unique name for this IKE proposal', max_length=100, unique=True, verbose_name='IKE Proposal Name'),
        ),
    ]
