# Generated by Django 5.1.7 on 2025-04-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecs', '0018_alter_ikeproposal_options_ikeproposal_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ikegateway',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ikepolicy',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipsecpolicy',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipsecproposal',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipsecvpn',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
