# Generated by Django 5.1.6 on 2025-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('Router', 'Router'), ('Switches', 'Switches'), ('Firewall', 'Firewall'), ('Loadbalancer', 'Loadbalancer')], default='Router', max_length=50)),
                ('vendor_name', models.CharField(choices=[('cisco', 'Cisco'), ('juniper', 'Juniper'), ('arista', 'Arista'), ('a10', 'A10')], default='cisco', max_length=50)),
                ('scope', models.CharField(choices=[('Core', 'Core'), ('Distribution', 'Distribution'), ('Firewall', 'Firewall'), ('Access', 'Access')], default='Core', max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('conn_protocol', models.CharField(choices=[('snmp', 'SNMP'), ('https', 'HTTPS API'), ('restconf', 'RESTCONF'), ('netconf', 'NETCONF')], default='snmp', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
