# Generated by Django 5.1.7 on 2025-04-24 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('router', 'router'), ('switch', 'switch'), ('firewall', 'firewall')], default='router', max_length=50)),
                ('vendor_name', models.CharField(choices=[('cisco', 'cisco'), ('juniper', 'juniper'), ('arista', 'arista')], default='cisco', max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_model', models.CharField(blank=True, max_length=50, null=True)),
                ('connection_protocol', models.CharField(blank=True, choices=[('ssh', 'SSH'), ('snmp', 'SNMP'), ('telnet', 'Telnet')], default='snmp', max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.site')),
            ],
        ),
    ]
