# Generated by Django 5.2 on 2025-05-05 06:03

import django.utils.timezone
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='connection_protocol',
            field=models.CharField(blank=True, choices=[('ssh', 'SSH'), ('snmp', 'SNMP'), ('telnet', 'Telnet'), ('netconf-ssh', 'netconf-ssh')], default='snmp', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
