# Generated by Django 5.1.7 on 2025-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.CharField(default='ams', max_length=10),
        ),
    ]
