# Generated by Django 5.1.6 on 2025-02-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('cisco', 'cisco'), ('juniper', 'juniper'), ('arista', 'arista'), ('a10', 'a10')], default='cisco', max_length=50),
        ),
    ]
