# Generated by Django 5.1.6 on 2025-02-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Router', 'Router'), ('Switches', 'Switches'), ('Firewall', 'Firewall'), ('Loadbalancer', 'Loadbalancer')], default='Router', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor_name',
            field=models.CharField(choices=[('cisco', 'Cisco'), ('juniper', 'Juniper'), ('arista', 'Arista'), ('a10', 'A10')], default='cisco', max_length=50),
        ),
    ]
