# Generated by Django 5.1.6 on 2025-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_alter_device_device_type_alter_device_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='scope',
            field=models.CharField(choices=[('Core', 'Core'), ('Distribution', 'Distribution'), ('Firewall', 'Firewall'), ('Access', 'Access')], default='Core', max_length=50),
        ),
    ]
