# Generated by Django 5.2.1 on 2025-05-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_interface'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interface',
        ),
    ]
