# Generated by Django 5.1.6 on 2025-02-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_alter_device_device_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='name',
        ),
    ]
