# Generated by Django 5.2.1 on 2025-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='keepalive',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('unknown', 'Unknown'), ('down', 'Down')], default='down', max_length=10),
        ),
    ]
