# Generated by Django 5.2.1 on 2025-05-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_device_keepalive_alter_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
