# Generated by Django 5.2.1 on 2025-05-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0004_delete_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down')], max_length=20, null=True)),
                ('speed', models.CharField(blank=True, max_length=20, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('interface_type', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='inventories.device')),
            ],
        ),
    ]
